"""create freebies table

Revision ID: 06c3680d6ebe
Revises: 864bb5434c61
Create Date: 2025-05-28 15:59:05.226217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c3680d6ebe'
down_revision = '864bb5434c61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
