"""initial migration

Revision ID: 864bb5434c61
Revises: 
Create Date: 2025-05-28 13:01:10.801971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864bb5434c61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('freebies',
    sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer, nullable=False),
    sa.Column('dev_id', sa.Integer, sa.ForeignKey('devs.id'), nullable=False),
    sa.Column('company_id', sa.Integer, sa.ForeignKey('companies.id'), nullable=False)
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    )

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('founding_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devs')
    op.drop_table('companies')
    op.drop_table('freebies')
    # ### end Alembic commands ###
